#!/bin/bash
# author:unclesz
# url:blog.unclezs.com
set -e
# 编译 上传到 page分支进行自动部署
yarn run build
cd docs/.vuepress/dist
git init
echo "uncle novel official pages" > README.md
git add -A .
git config user.name "unclezs"
git config user.email "unclezs@qq.com"
git commit -a -m "${1:-'update'}" --branch
git remote add origin git@github.com:unclezs/uncle-novel-official-site.git
git branch page
git push -f -u origin page
cd -
# 源码上传到main

git add -A . 
git commit -m "${1:-'update'}"
git push -u origin main

